defaults:
  cluster: ${CLUSTER}
  environment:
    name: '"sfdemo-" ~ code_reference.branch'

variables:
  - name: SYMFONY_ENV
    value: prod
  - name: DEVELOPMENT_MODE
    value: 1

tasks:
  images:
    build:
      services:
        web:
          image: ${IMAGE_NAME}
          naming_strategy: sha1
  deployment:
    deploy:
      services:
        web:
          specification:
            accessibility:
              from_external: true
            environment_variables:
              - name: SYMFONY_ENV
                value: ${SYMFONY_ENV}
              - name: DEVELOPMENT_MODE
                value: ${DEVELOPMENT_MODE}


pipelines:
  - name: Production
    condition: 'not(code_reference.branch matches "/^cpdev/")'
    tasks: [ images, deployment ]
  - name: Remote
    condition: 'code_reference.branch matches "/^cpdev/"'
    tasks: [ images, deployment ]
    variables:
      - name: SYMFONY_ENV
        value: dev
      - name: DEVELOPMENT_MODE
        value: 0


